src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Groups("main")
     */
    private $email;



    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("main")
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $token;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="User")
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Tricks", mappedBy="author")
     */
    private $tricks;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Picture;

    public function __construct()
    {
        $this->roles = ['ROLE_MEMBER'] ;
        $this->comments = new ArrayCollection();
        $this->tricks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */


    public function getUsername(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken($token)
    {
        $this->token = $token;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }


    /**
     * @return Collection|Tricks[]
     */
    public function getTricks(): Collection
    {
        return $this->tricks;
    }

    public function addTrick(Tricks $trick): self
    {
        if (!$this->tricks->contains($trick)) {
            $this->tricks[] = $trick;
            $trick->setAuthor($this);
        }

        return $this;
    }

    public function removeTrick(Tricks $trick): self
    {
        if ($this->tricks->contains($trick)) {
            $this->tricks->removeElement($trick);
            // set the owning side to null (unless already changed)
            if ($trick->getAuthor() === $this) {
                $trick->setAuthor(null);
            }
        }

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->Picture;
    }

    public function setPicture(?string $Picture): self
    {
        $this->Picture = $Picture;

        return $this;
    }
}

templates/Member/addTricks.html.twig
{% extends 'base.html.twig' %}
{% block title %} Add tricks {% endblock %}
{% block body %}

    <br/><br/><br/><br/>
    <div class="center-block example-wrapper text-center">
    <h1>Launch a new Tricks! ?</h1>
    {{ form_start(addTricksForm) }}


        {{ form_row(addTricksForm.name) }}
        {{ form_row(addTricksForm.description) }}
        {{ form_row(addTricksForm.categoryTricks) }}

        <div class="row js-genus-scientist-wrapper data"
            data-prototype ="{{ form_widget(addTricksForm.Illustration.vars.prototype)|e('html_attr') }}"
             data-index="{{ addTricksForm.Illustration|length }}">


            <div class="col-lg-11">
                <a href="#" class="js-genus-scientist-add" id="add_button_media">
                    <span class="fa fa-plus-circle"></span>
                    Add Image to this tricks
                </a>
            </div>
        </div>


        <hr>

        <div class="row js-embed-scientist-wrapper data"
             data-prototype ="{{ form_widget(addTricksForm.Embed.vars.prototype)|e('html_attr') }}"
             data-index="{{ addTricksForm.Embed|length }}">

            <div class="col-lg-11">
                <a href="#" class="js-embed-scientist-add" id="add_button_embed">
                    <span class="fa fa-plus-circle"></span>
                    Add Embed Balise
                </a>
            </div>
        </div>


            <br/><br/><br/>
            <button type="submit" class="btn btn-primary submit">Create!</button><br/><br/>
            {% do addTricksForm.Illustration.setRendered() %}
            {{ form_end(addTricksForm) }}


    </div>
{% endblock %}

{% block javascripts %}

    {{ parent() }}

    <script
            src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous">

    </script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" type="text/css"/>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <script>
        var element = document.getElementById('data');

        jQuery(document).ready(function() {
            var $wrapper = $('.js-genus-scientist-wrapper');
            $wrapper.on('click', '.js-remove-scientist', function(e) {
                e.preventDefault();
                $(this).closest('.js-genus-scientist-item')
                    .fadeOut()
                    .remove();
            });
            $wrapper.on('click', '.js-genus-scientist-add', function(e) {
                e.preventDefault();
                var prototype = $wrapper.data('prototype');
                var index = $wrapper.data('index');
                var newForm = prototype.replace(/__name__/g, index);
                $wrapper.data('index', index + 1 );
                console.log(index);
                $(this).before(newForm);
            });
            var $wrapperEmbed = $('.js-embed-scientist-wrapper');
            $wrapperEmbed.on('click', '.js-embed-scientist-add', function(e) {
                e.preventDefault();
                var prototype = $wrapperEmbed.data('prototype');
                var embedIndex = $wrapperEmbed.data('index');
                var newForm = prototype.replace(/__name__/g, embedIndex);
                $wrapperEmbed.data('index', embedIndex + 1);
                $(this).before(newForm);
            });


        });
    </script>
{% endblock %}

templates/Member/dashboard.html.twig
{% extends 'base.html.twig' %}

{% block title %} my profile {% endblock %}
{% block body %}
    <br/><br/><br/><br/>

    <section class="d-flex justify-content-center">
        <h3>Welcome back, {{ app.user.Username }}</h3>
    </section>

    <div class="container ">

        <div class="col-lg-5">
            {% if app.user.picture is defined %}
                <img class="img-fluid" src="img/user/{{ app.user.picture }}" width="10%"/><br/><br/>
            {% else %}
                <img class="img-fluid" src="img/user/0.jpg" width="10%"/><br/><br/>
            {% endif %}
            <p> mail: {{ app.user.email }} </p>
            <p> numéro d'inscrit: {{ app.user.id }}</p>
            <p> username: {{ app.user.Username }}</p>
        </div>

        <div class="example-wrapper">
            {{ form_start(UserPictureFormType) }}
            {{ form_widget(UserPictureFormType) }}
            <button type="submit" class="btn btn-primary">Upload an image</button>
            {{ form_end(UserPictureFormType) }}
        </div>

        <button type="button" class="btn btn-warning"><a data-toggle="modal" href="#modalpassword">Change my password</a> </button>


        <!-- DELETE MODALS -->
        <div class="modal myModal" id="modalpassword" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Change my password </h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">

                        {{ form_start(UserPasswordFormType) }}
                        {{ form_widget(UserPasswordFormType) }}
                        <button type="submit" class="btn btn-primary">Change my password </button>
                        {{ form_end(UserPasswordFormType) }}

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

    </div>





{% endblock %}

templates/Member/editTricks.html.twig
{% extends 'base.html.twig' %}

{% block title %} Edit Tricks {% endblock %}
{% block body %}
    <br/><br/><br/><br/>
    <div class="center-block example-wrapper">
        <h1>Edit tricks : {{ trick.name }}</h1>

        {{ form_start(addTricksForm) }}

        {{ form_row(addTricksForm.name) }}
        {{ form_row(addTricksForm.description) }}
        {{ form_row(addTricksForm.categoryTricks) }}

        <div class="row js-genus-scientist-wrapper data"
             data-prototype ="{{ form_widget(addTricksForm.Illustration.vars.prototype)|e('html_attr') }}"
             data-index="{{ addTricksForm.Illustration|length }}">
            <div class="add_button">
                <div class="col-lg-11">
                    <a href="#" class="js-genus-scientist-add">
                        <span class="fa fa-plus-circle"></span>
                        Add Image to this tricks
                    </a>
                </div>
            </div>
        </div>

        <hr>
        <div class="row js-embed-scientist-wrapper data"
             data-prototype ="{{ form_widget(addTricksForm.Embed.vars.prototype)|e('html_attr') }}"
             data-index="{{ addTricksForm.Embed|length }}">


            <div class="col-lg-11">
                <a href="#" class="js-embed-scientist-add">
                    <span class="fa fa-plus-circle"></span>
                    Add Embed Balise
                </a>
            </div>
        </div>
            <br/><br/><br/>
            <button type="submit" class="btn btn-primary submit">Update this Tricks</button><br/><br/>

            {% do addTricksForm.Illustration.setRendered() %}
            {{ form_end(addTricksForm) }}


            <hr>

            <div class="row">
                <div class="col-lg-5 center-block">
                <h1>Media for this tricks</h1>
                </div>
            </div>


            <div class="row">

                {% for i in 0..10 %}
                    {%  if  trick.Illustration[i].path is defined and trick.Illustration[i].type == 'Picture' %}
                        <div class="col-lg-11 center-block text-center">
                            <img src="{{ asset('img/'~trick.Illustration[i].path) }}" alt="{{ trick.Illustration[i].texte }}" /><br/>
                            <a data-toggle="modal" href="#myModal0">Delete Image</a><br/>
                            <a href="{{ path('select_thumbnail', { id: trick.Illustration[i].id, trick: trick.id}) }}"  class="btn btn-primary">Select for thumbnails </a>
                            <hr>
                        </div>

                        <!-- DELETE MODALS -->
                        <div class="modal myModal" id="myModal0" tabindex="-1" role="dialog">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">Delete an image</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <p>Your are sure to delete this image ?  </p>
                                    </div>
                                    <div class="modal-footer">
                                        <a href="{{ path('image_delete', { id: trick.Illustration[i].id}) }}" type="button" class="btn btn-primary">Delete </a>
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                    {% endif %}

                {% endfor %} <br/>

                <!------------- EMBED AFFICHAGE ET MODALS DELETE -------------------->

                {% for i in 0..10 %}
                    {%  if trick.Illustration[i].path is defined  %}
                        {% if trick.Illustration[i].type == 'Embed' %}
                        <div>
                            {{ trick.Illustration[i].path|html }}<br/>
                            <a data-toggle="modal" href="#myModal10">Delete Embed Balise</a>
                        </div>

                        <!-- DELETE MODALS -->
                        <div class="modal myModal" id="myModal10" tabindex="-1" role="dialog">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">Delete an Embed Balise</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <p>Your are sure to delete Embed Balise ?  </p>
                                    </div>
                                    <div class="modal-footer">
                                        <a href="{{ path('embed_delete', { id: trick.Illustration[i].id}) }}" type="button" class="btn btn-primary">Delete </a>
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    {% endif %}
                {% endfor %}


            </div>

    </div>
    <br/><br/><br/><br/><br/>

{% endblock %}

{% block javascripts %}

    {{ parent() }}

    <script
            src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous">

    </script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" type="text/css"/>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <script>
        var element = document.getElementById('data');

        jQuery(document).ready(function() {
            var $wrapper = $('.js-genus-scientist-wrapper');
            $wrapper.on('click', '.js-remove-scientist', function(e) {
                e.preventDefault();
                $(this).closest('.js-genus-scientist-item')
                    .fadeOut()
                    .remove();
            });
            $wrapper.on('click', '.js-genus-scientist-add', function(e) {
                e.preventDefault();
                var prototype = $wrapper.data('prototype');
                var index = $wrapper.data('index');
                var newForm = prototype.replace(/__name__/g, index);
                $wrapper.data('index', index + 1 );
                console.log(index);
                $(this).before(newForm);
            });
            var $wrapperEmbed = $('.js-embed-scientist-wrapper');
            $wrapperEmbed.on('click', '.js-embed-scientist-add', function(e) {
                e.preventDefault();
                var prototype = $wrapperEmbed.data('prototype');
                var embedIndex = $wrapperEmbed.data('index');
                var newForm = prototype.replace(/__name__/g, embedIndex);
                $wrapperEmbed.data('index', embedIndex + 1);
                $(this).before(newForm);
            });


        });
    </script>
{% endblock %}

templates/Member/listTricks.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <br/><br/><br/><br/>
    <div class="center-block example-wrapper">

        <a href="{{ path('admin_tricks_new') }}" class="btn btn-primary center-block text-center">
            Create <span class="fa fa-plus-circle"></span>
        </a>
        <br/><br/>
        <h1>My SnowTricks</h1>

        <table class="table">
            <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Edit</th>
                <th> Delete </th>

            </tr>
            </thead>
            <tbody>
            {% for trick in tricks %}
                {%  if trick.author.username == visitorName %}
                <tr>
                    <td>{{ trick.name }}</td>
                    <td>{{ trick.description }}</td>
                    <td>
                        <a href="{{ path('admin_article_edit', {
                            tricks: trick.id
                        }) }}">Edit
                            <span class="fa fa-pencil"></span>
                        </a>
                    </td>

                    <td>
                        <a data-toggle="modal" href="#myModal"><i class="fas fa-trash-alt"></i></a>

                        <!-- DELETE MODALS -->
                        <div class="modal myModal" id="myModal" tabindex="-1" role="dialog">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">Delete on tricks</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <p>Are you sure you want to delete this trick as well as the media and commentary that accompanies it? </p>
                                    </div>
                                    <div class="modal-footer">
                                        <a href="{{ path('admin_trick_delete', { id: trick.id}) }}" type="button" class="btn btn-primary">Delete </a>
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </td>


                </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/Member/login.html.twig
{% extends 'base.html.twig' %}

{% block title %} Sign IN {% endblock %}
{% block body %}

    <br/><br/><br/><br/>


<div class="example-wrapper">
    <h1 id="connexion">Connexion</h1>
</div>

<form action="{{ path('login') }}" method="post">
    <label for="username">Username:</label>
    <input type="text" id="username" name="_username" value="" />

    <label for="password">Password:</label>
    <input type="password" id="password" name="_password" />

    <button class="btn" type="submit">login</button>
</form>

{% endblock %}

templates/Member/myprofile.html.twig
{% extends 'base.html.twig' %}

{% block title %} my profile {% endblock %}
{% block body %}
    <br/><br/><br/><br/>

    <section class="d-flex justify-content-center">
        <h3>  Your profile : {{ visitorName }}</h3>
    </section>

    <div class="row">

    </div>

{% endblock %}